import { db } from "./index";
import { categories, posts, importantLinks, adminUsers, newsTicker } from "./schema";
import { hashPassword } from "../lib/auth";
import { eq } from "drizzle-orm";

export async function runSeed() {
  console.log("🚀 Starting database seeding for OnlineWallah.com...");

  // 1. Categories
  const categoryData = [
    { name: "Latest Jobs", slug: "latest-jobs", icon: "Briefcase", description: "All latest Government & Public Institution recruitment notifications", displayOrder: 1 },
    { name: "Results", slug: "results", icon: "FileCheck", description: "Government exam results, merit lists, and score cards", displayOrder: 2 },
    { name: "Admit Card", slug: "admit-card", icon: "IdCard", description: "Hall tickets, call letters, and exam city intimation slips", displayOrder: 3 },
    { name: "Answer Key", slug: "answer-key", icon: "Key", description: "Official exam answer keys, question papers, and objection forms", displayOrder: 4 },
    { name: "Syllabus", slug: "syllabus", icon: "BookOpen", description: "Detailed syllabus, exam patterns, marking schemes, and previous papers", displayOrder: 5 },
    { name: "Admission", slug: "admission", icon: "GraduationCap", description: "National entrance exams, university admissions, and counseling forms", displayOrder: 6 },
    { name: "Engineering Jobs", slug: "engineering", icon: "Cog", description: "PSUs, GATE recruitment, Junior Engineer (JE), and Technical posts", displayOrder: 7 },
  ];

  for (const cat of categoryData) {
    const existing = await db.select().from(categories).where(eq(categories.slug, cat.slug));
    if (existing.length === 0) {
      await db.insert(categories).values(cat);
    }
  }
  console.log("✅ Categories seeded");

  // 2. Admin User
  const adminCheck = await db.select().from(adminUsers).where(eq(adminUsers.username, "admin"));
  if (adminCheck.length === 0) {
    const passwordHash = await hashPassword("AdminPassword2026!");
    await db.insert(adminUsers).values({
      username: "admin",
      email: "admin@onlinewallah.com",
      passwordHash,
      role: "admin",
    });
    console.log("✅ Admin user created (username: admin, password: AdminPassword2026!)");
  }

  // 3. News Ticker items
  const tickerItems = [
    { message: "UPSC Civil Services IAS 2026 Notification Out — Apply Online for 1,105 Posts", linkUrl: "/latest-jobs/upsc-ias-recruitment-2026", badgeText: "NEW", displayOrder: 1, isActive: true },
    { message: "SSC CGL 2026 Tier 1 Result & Cut Off Marks Released — Check Score Card", linkUrl: "/results/ssc-cgl-tier-1-result-2026", badgeText: "OUT", displayOrder: 2, isActive: true },
    { message: "Railway RRB ALP Assistant Loco Pilot 2026 Exam City Slip & Admit Card Released", linkUrl: "/admit-card/rrb-alp-admit-card-2026", badgeText: "ALERT", displayOrder: 3, isActive: true },
    { message: "NEET UG 2026 Online Registration Window Extended till 15th April", linkUrl: "/admission/nta-neet-ug-admission-2026", badgeText: "UPDATED", displayOrder: 4, isActive: true },
    { message: "UP Police Constable 2026 Written Exam Answer Key Objection Window Open", linkUrl: "/answer-key/up-police-constable-answer-key-2026", badgeText: "NEW", displayOrder: 5, isActive: true },
  ];

  for (const ticker of tickerItems) {
    await db.insert(newsTicker).values(ticker);
  }
  console.log("✅ News Ticker seeded");

  // 4. Important Links Portals
  const portals = [
    { label: "UPSC Official Portal", url: "https://upsc.gov.in", category: "UPSC", description: "Union Public Service Commission", displayOrder: 1 },
    { label: "SSC Official Portal (New)", url: "https://ssc.gov.in", category: "SSC", description: "Staff Selection Commission", displayOrder: 2 },
    { label: "Indian Railways (RRB Recruitment)", url: "https://indianrailways.gov.in", category: "Railway", description: "Railway Recruitment Boards", displayOrder: 3 },
    { label: "National Testing Agency (NTA)", url: "https://nta.ac.in", category: "NTA", description: "NEET, JEE, CUET, UGC NET Exams", displayOrder: 4 },
    { label: "Institute of Banking Personnel (IBPS)", url: "https://ibps.in", category: "Banking", description: "Bank PO, Clerk, SO Recruitment", displayOrder: 5 },
    { label: "State Bank of India Careers", url: "https://sbi.co.in/web/careers", category: "Banking", description: "SBI PO, Clerk, Specialist Officer", displayOrder: 6 },
    { label: "Uttar Pradesh PSC (UPPSC)", url: "https://uppsc.up.nic.in", category: "State PSC", description: "UP Combined State Subordinate Services", displayOrder: 7 },
    { label: "Bihar Public Service Commission (BPSC)", url: "https://bpsc.bih.nic.in", category: "State PSC", description: "BPSC Civil Services & Teachers", displayOrder: 8 },
    { label: "Rajasthan RSSB / RPSC", url: "https://rpsc.rajasthan.gov.in", category: "State PSC", description: "Rajasthan Public Service Commission", displayOrder: 9 },
    { label: "Central Teacher Eligibility Test (CTET)", url: "https://ctet.nic.in", category: "Teaching", description: "CBSE National Teacher Eligibility Test", displayOrder: 10 },
    { label: "Indian Army Join Army", url: "https://joinindianarmy.nic.in", category: "Defense", description: "Indian Army Officers & Agniveer", displayOrder: 11 },
    { label: "Indian Air Force AFCAT", url: "https://afcat.cdac.in", category: "Defense", description: "Air Force Common Admission Test", displayOrder: 12 },
    { label: "DRDO Official Recruitment", url: "https://drdo.gov.in", category: "Engineering", description: "Defense Research & Development Org", displayOrder: 13 },
    { label: "ISRO ICRB Portal", url: "https://isro.gov.in/careers", category: "Engineering", description: "Indian Space Research Organisation", displayOrder: 14 },
    { label: "Delhi Subordinate Services (DSSSB)", url: "https://dsssb.delhi.gov.in", category: "State PSC", description: "Govt of NCT Delhi Jobs", displayOrder: 15 },
  ];

  for (const portal of portals) {
    await db.insert(importantLinks).values(portal);
  }
  console.log("✅ Important Portals seeded");

  // 5. Rich Posts across categories
  const samplePosts = [
    // --- LATEST JOBS ---
    {
      title: "UPSC Civil Services IAS / IFS Recruitment 2026 Online Form",
      slug: "upsc-ias-recruitment-2026",
      category: "latest-jobs",
      subcategory: "UPSC",
      year: 2026,
      organization: "Union Public Service Commission (UPSC)",
      totalVacancies: "1,105 Posts",
      qualificationSummary: "Bachelor Degree in Any Stream",
      shortDesc: "Union Public Service Commission (UPSC) has released notification for Civil Services Prelims (IAS) and Indian Forest Service (IFS) Examination 2026.",
      status: "published",
      isPinned: true,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Application Begin", value: "14/02/2026" },
        { label: "Last Date for Apply Online", value: "05/03/2026 upto 06:00 PM", isHighlight: true },
        { label: "Pay Exam Fee Last Date", value: "05/03/2026" },
        { label: "Correction Window Period", value: "06/03/2026 to 12/03/2026" },
        { label: "Pre Exam Date", value: "24/05/2026", isHighlight: true },
        { label: "Admit Card Available", value: "May 2026" },
      ],
      applicationFee: [
        { category: "General / OBC / EWS", fee: "₹ 100/-" },
        { category: "SC / ST / PH", fee: "₹ 0/- (Nil)" },
        { category: "All Category Female", fee: "₹ 0/- (Exempted)" },
      ],
      feePaymentMode: "Pay the Examination Fee Through Debit Card, Credit Card, Net Banking or Pay Offline Through E-Challan at State Bank of India.",
      ageLimit: {
        minAge: "21 Years",
        maxAge: "32 Years",
        asOnDate: "01/08/2026",
        extraNotes: "Age relaxation applicable: OBC 3 Years, SC/ST 5 Years, PwD 10 Years as per UPSC Civil Services Examination 2026 rules.",
      },
      vacancyDetails: [
        { postName: "Indian Administrative Service (IAS)", totalPosts: "955", eligibility: "Bachelor Degree in Any Stream from Any Recognized University in India.", ageLimit: "21-32 Years" },
        { postName: "Indian Forest Service (IFS)", totalPosts: "150", eligibility: "Bachelor Degree with at least one subject: Animal Husbandry & Veterinary Science, Botany, Chemistry, Geology, Mathematics, Physics, Statistics and Zoology or Agriculture.", ageLimit: "21-32 Years" },
      ],
      importantLinks: [
        { label: "Apply Online (OTR Registration)", url: "https://upsconline.nic.in", linkType: "apply", isHighlighted: true },
        { label: "Download IAS Official Notification (English)", url: "https://upsc.gov.in/notifications", linkType: "notification" },
        { label: "Download IFS Official Notification (English)", url: "https://upsc.gov.in/notifications", linkType: "notification" },
        { label: "Official UPSC Website", url: "https://upsc.gov.in", linkType: "official_website" },
        { label: "Join OnlineWallah Telegram Channel", url: "https://t.me/onlinewallah", linkType: "other" },
      ],
      howToApply: [
        "Candidates must complete the One Time Registration (OTR) on the official UPSC portal upsc.gov.in before filling the examination application form.",
        "Ensure personal details, photograph (with name and date), and signature match UPSC guidelines.",
        "Upload required valid photo ID card (Aadhaar Card / Voter ID / PAN Card / Passport / Driving License).",
        "Pay the online application fee of ₹100/- (Females/SC/ST/PH are exempted).",
        "Verify all entered details carefully before final submission. Note down the registration number and print the confirmation page.",
      ],
      selectionProcess: [
        "Stage 1: Preliminary Examination (Objective Type - GS Paper I & CSAT Paper II)",
        "Stage 2: Main Written Examination (Descriptive 9 Papers)",
        "Stage 3: Personality Test / Interview",
        "Stage 4: Medical Examination & Final Merit List",
      ],
      metaTitle: "UPSC IAS / IFS Recruitment 2026 Notification Out - Apply Online for 1105 Posts",
      metaDescription: "UPSC Civil Services 2026 online application form, exam date, eligibility criteria, age limit, syllabus and direct official link.",
    },
    {
      title: "SSC CGL Recruitment 2026 Combined Graduate Level Exam (17,727 Vacancies)",
      slug: "ssc-cgl-recruitment-2026",
      category: "latest-jobs",
      subcategory: "SSC",
      year: 2026,
      organization: "Staff Selection Commission (SSC)",
      totalVacancies: "17,727 Posts",
      qualificationSummary: "Graduation in Any Stream",
      shortDesc: "Staff Selection Commission has announced SSC CGL 2026 Exam for Group B and Group C Officers in various Central Ministries and Departments.",
      status: "published",
      isPinned: true,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Application Begin", value: "24/06/2026" },
        { label: "Last Date for Apply Online", value: "27/07/2026 upto 11:00 PM", isHighlight: true },
        { label: "Last Date Fee Payment", value: "28/07/2026" },
        { label: "Correction Date", value: "10-11 August 2026" },
        { label: "Tier 1 Exam Date", value: "September / October 2026", isHighlight: true },
      ],
      applicationFee: [
        { category: "General / OBC / EWS", fee: "₹ 100/-" },
        { category: "SC / ST / ESM / PH", fee: "₹ 0/- (Nil)" },
        { category: "All Category Female", fee: "₹ 0/- (Nil)" },
      ],
      feePaymentMode: "Pay through BHIM UPI, Net Banking, Visa, MasterCard, Maestro, RuPay Credit or Debit cards.",
      ageLimit: {
        minAge: "18 Years",
        maxAge: "30-32 Years (Post Wise)",
        asOnDate: "01/08/2026",
        extraNotes: "Age relaxation as per Staff Selection Commission Combined Graduate Level rules.",
      },
      vacancyDetails: [
        { postName: "Assistant Section Officer (ASO) in CSS / MEA / IB", totalPosts: "3,200", eligibility: "Bachelor Degree in Any Stream from recognized university.", ageLimit: "20-30 Years" },
        { postName: "Income Tax Inspector / Central Excise Inspector (CBIC)", totalPosts: "4,500", eligibility: "Bachelor Degree in Any Stream.", ageLimit: "18-30 Years" },
        { postName: "Junior Statistical Officer (JSO)", totalPosts: "750", eligibility: "Bachelor Degree with 60% in Mathematics at 12th Std OR Degree with Statistics as a subject.", ageLimit: "18-32 Years" },
        { postName: "Auditor / Accountant / Tax Assistant", totalPosts: "9,277", eligibility: "Bachelor Degree in Any Stream.", ageLimit: "18-27 Years" },
      ],
      importantLinks: [
        { label: "Apply Online (SSC New Portal)", url: "https://ssc.gov.in", linkType: "apply", isHighlighted: true },
        { label: "Download CGL Detailed Notification PDF", url: "https://ssc.gov.in", linkType: "notification" },
        { label: "Official SSC Portal", url: "https://ssc.gov.in", linkType: "official_website" },
      ],
      howToApply: [
        "Visit the new SSC portal ssc.gov.in and complete candidate registration.",
        "Capture live web-camera photo adhering to the lighting guidelines.",
        "Upload scanned signature and choose preferred examination centers.",
        "Complete online fee payment and download final submitted application.",
      ],
      selectionProcess: ["Tier 1 CBT Computer Based Exam", "Tier 2 CBT Computer Based Exam + DEST Typing Test", "Document Verification & Medical Test"],
      metaTitle: "SSC CGL 2026 Notification - 17,727 Group B & C Vacancies Apply Online",
      metaDescription: "Staff Selection Commission SSC CGL 2026 vacancy details, syllabus, exam dates and direct link to apply online at ssc.gov.in.",
    },
    {
      title: "Railway RRB ALP (Assistant Loco Pilot) Recruitment 2026 (18,799 Posts)",
      slug: "rrb-alp-recruitment-2026",
      category: "latest-jobs",
      subcategory: "Railway",
      year: 2026,
      organization: "Railway Recruitment Boards (RRB - CEN 01/2026)",
      totalVacancies: "18,799 Posts",
      qualificationSummary: "10th Pass + ITI / Diploma / BE / B.Tech",
      shortDesc: "Railway Recruitment Boards (RRB) invite online applications for 18,799 Assistant Loco Pilot vacancies across all Indian Railway zones.",
      status: "published",
      isPinned: true,
      isNew: false,
      isUpdated: true,
      importantDates: [
        { label: "Notification Date", value: "20/01/2026" },
        { label: "Application End Date", value: "19/02/2026", isHighlight: true },
        { label: "CBT 1 Exam Date", value: "June - July 2026", isHighlight: true },
      ],
      applicationFee: [
        { category: "Gen / OBC / EWS", fee: "₹ 500/- (₹400 refunded after appearing in CBT-1)" },
        { category: "SC / ST / Ex-SM / Female / Transgender / Minorities / EBC", fee: "₹ 250/- (Full refunded after appearing in CBT-1)" },
      ],
      feePaymentMode: "Online Payment via Net Banking, Debit / Credit Card, UPI.",
      ageLimit: { minAge: "18 Years", maxAge: "33 Years (3-year one-time relaxation included)", asOnDate: "01/07/2026" },
      vacancyDetails: [
        { postName: "Assistant Loco Pilot (Electrical & Mechanical)", totalPosts: "18,799", eligibility: "Matriculation / 10th Pass + ITI in relevant trade OR Diploma in Mechanical / Electrical / Electronics / Automobile Engineering OR Degree in Engineering.", ageLimit: "18-33 Years" },
      ],
      importantLinks: [
        { label: "Apply Online (RRB Regional Portals)", url: "https://www.rrbapply.gov.in", linkType: "apply", isHighlighted: true },
        { label: "Download CEN 01/2026 Official Notification PDF", url: "https://indianrailways.gov.in", linkType: "notification" },
        { label: "RRB Official Website", url: "https://indianrailways.gov.in", linkType: "official_website" },
      ],
      howToApply: ["Register on rrbapply.gov.in", "Choose preferred RRB zone", "Upload documents & pay fee", "Save application receipt"],
      selectionProcess: ["CBT 1 First Stage", "CBT 2 Second Stage (Part A + Part B)", "CBAT Computer Based Aptitude Test", "Document Verification & Medical"],
      metaTitle: "Railway RRB ALP Recruitment 2026 - 18,799 Posts Apply Online",
      metaDescription: "RRB Assistant Loco Pilot recruitment 2026 online form, qualification, syllabus, salary pay matrix and exam date.",
    },
    {
      title: "State Bank of India (SBI) PO Recruitment 2026 (2,000 Posts)",
      slug: "sbi-po-recruitment-2026",
      category: "latest-jobs",
      subcategory: "Banking",
      year: 2026,
      organization: "State Bank of India (SBI)",
      totalVacancies: "2,000 Posts",
      qualificationSummary: "Graduation in Any Discipline",
      shortDesc: "SBI Probationary Officers recruitment 2026 notification released for 2000 vacancies across SBI branches in India.",
      status: "published",
      isPinned: false,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Application Start", value: "07/03/2026" },
        { label: "Last Date to Apply", value: "27/03/2026", isHighlight: true },
        { label: "Prelims Exam Date", value: "May 2026" },
        { label: "Mains Exam Date", value: "July 2026" },
      ],
      applicationFee: [
        { category: "General / EWS / OBC", fee: "₹ 750/-" },
        { category: "SC / ST / PwBD", fee: "₹ 0/- (Nil)" },
      ],
      feePaymentMode: "Online Payment Gateway",
      ageLimit: { minAge: "21 Years", maxAge: "30 Years", asOnDate: "01/04/2026" },
      vacancyDetails: [
        { postName: "Probationary Officer (PO)", totalPosts: "2,000", eligibility: "Graduation in any discipline from a recognized University or equivalent.", ageLimit: "21-30 Years" },
      ],
      importantLinks: [
        { label: "Apply Online (SBI IBPS Portal)", url: "https://ibpsonline.ibps.in/sbipomarch26", linkType: "apply", isHighlighted: true },
        { label: "Download SBI PO Official Notification PDF", url: "https://sbi.co.in/careers", linkType: "notification" },
        { label: "SBI Official Careers Website", url: "https://sbi.co.in/careers", linkType: "official_website" },
      ],
      howToApply: ["Register on SBI IBPS portal", "Fill personal and academic credentials", "Upload photo, thumb impression, and hand-written declaration", "Pay ₹750 fee"],
      selectionProcess: ["Phase I: Preliminary Examination", "Phase II: Main Examination (Objective + Descriptive)", "Phase III: Psychometric Test, Group Exercise & Interview"],
      metaTitle: "SBI PO Recruitment 2026 Notification - 2000 Probationary Officer Posts",
      metaDescription: "Apply online for SBI PO 2026 examination, exam pattern, eligibility and direct notification PDF download.",
    },
    {
      title: "UP Police Constable Recruitment 2026 (60,244 Posts Re-Exam)",
      slug: "up-police-constable-recruitment-2026",
      category: "latest-jobs",
      subcategory: "Police",
      year: 2026,
      organization: "Uttar Pradesh Police Recruitment and Promotion Board (UPPRPB)",
      totalVacancies: "60,244 Posts",
      qualificationSummary: "10+2 Intermediate Passed",
      shortDesc: "UP Police Constable recruitment 2026 for 60,244 Civil Police Constables in Uttar Pradesh.",
      status: "published",
      isPinned: false,
      isNew: false,
      isUpdated: true,
      importantDates: [
        { label: "Application Completed", value: "January 2026" },
        { label: "Re-Exam Date", value: "23 to 31 August 2026", isHighlight: true },
        { label: "City Intimation", value: "16 August 2026" },
      ],
      applicationFee: [{ category: "All Candidates", fee: "₹ 400/-" }],
      feePaymentMode: "Online via E-Challan / Debit / Credit Card / Net Banking",
      ageLimit: { minAge: "18 Years", maxAge: "25 Years (Male) / 28 Years (Female)", asOnDate: "01/07/2026" },
      vacancyDetails: [
        { postName: "Constable Civil Police", totalPosts: "60,244", eligibility: "10+2 Intermediate Exam Passed from Any Recognized Board in India.", ageLimit: "18-25 Years" },
      ],
      importantLinks: [
        { label: "Check Exam City Slip", url: "https://uppbpb.gov.in", linkType: "admit_card", isHighlighted: true },
        { label: "Official UPPRPB Website", url: "https://uppbpb.gov.in", linkType: "official_website" },
      ],
      howToApply: ["Visit uppbpb.gov.in to check roll number and allocated exam district.", "Carry original Aadhaar card and admit card to exam center."],
      selectionProcess: ["Written Examination (OMR Based)", "Document Verification & Physical Standard Test (PST)", "Physical Efficiency Test (PET Run)"],
      metaTitle: "UP Police Constable Recruitment 2026 - 60,244 Vacancies Exam Updates",
      metaDescription: "Uttar Pradesh Police Constable 60244 posts re-exam dates, admit card download and syllabus at uppbpb.gov.in.",
    },

    // --- RESULTS ---
    {
      title: "SSC CGL Tier 1 Result 2026 & Cut Off Marks Released",
      slug: "ssc-cgl-tier-1-result-2026",
      category: "results",
      subcategory: "SSC",
      year: 2026,
      organization: "Staff Selection Commission (SSC)",
      totalVacancies: "17,727 Posts",
      qualificationSummary: "Graduate Level Examination",
      shortDesc: "Staff Selection Commission has declared SSC Combined Graduate Level (CGL) 2026 Tier-I Computer Based Examination Result, Cutoff Marks and Qualified Candidates List for Tier 2.",
      status: "published",
      isPinned: true,
      isNew: true,
      isUpdated: true,
      importantDates: [
        { label: "Tier 1 Exam Date", value: "09 to 26 September 2026" },
        { label: "Answer Key Released", value: "03 October 2026" },
        { label: "Tier 1 Result Declared", value: "Today (Official)", isHighlight: true },
        { label: "Tier 2 Exam Date", value: "18 to 20 January 2027", isHighlight: true },
      ],
      applicationFee: [{ category: "Result Verification", fee: "₹ 0/- (Free)" }],
      feePaymentMode: "Free to Check & Download PDF",
      ageLimit: { minAge: "18 Years", maxAge: "32 Years", asOnDate: "01/08/2026" },
      vacancyDetails: [
        { postName: "List 1: Candidates Qualified for JSO", totalPosts: "3,140 Qualified", eligibility: "Shortlisted based on Tier 1 Normalized Score", ageLimit: "18-32 Years" },
        { postName: "List 2: Candidates Qualified for Statistical Investigator Gr. II", totalPosts: "2,420 Qualified", eligibility: "Shortlisted based on Tier 1", ageLimit: "18-30 Years" },
        { postName: "List 3: Candidates Qualified for All Other Group B & C Posts", totalPosts: "1,42,860 Qualified", eligibility: "Cut Off UR: 153.25, OBC: 148.10, EWS: 145.80, SC: 128.50, ST: 119.20", ageLimit: "18-30 Years" },
      ],
      importantLinks: [
        { label: "Download Tier 1 Result PDF (List 3 - All Other Posts)", url: "https://ssc.gov.in/results", linkType: "result", isHighlighted: true },
        { label: "Download Tier 1 Cut Off Marks & Writeup PDF", url: "https://ssc.gov.in/results", linkType: "result", isHighlighted: true },
        { label: "Check Individual Marks & Score Card (Login)", url: "https://ssc.gov.in", linkType: "result" },
        { label: "Official SSC Website", url: "https://ssc.gov.in", linkType: "official_website" },
      ],
      howToApply: [
        "Click on the 'Download Result PDF' link above.",
        "Open the downloaded PDF file on your mobile device or computer.",
        "Press 'Ctrl + F' or use the search icon in your PDF viewer.",
        "Enter your Roll Number or Candidate Name to check qualification status.",
        "If your Roll Number appears in the list, you have qualified for the SSC CGL Tier 2 Exam.",
      ],
      selectionProcess: ["Tier 1 Exam (Cleared)", "Tier 2 Exam (Coming Soon)", "DEST Typing Test", "Document Verification"],
      metaTitle: "SSC CGL Tier 1 Result 2026 Cut Off Marks & Merit List PDF Download",
      metaDescription: "Download SSC CGL 2026 Tier 1 result PDF, category-wise cutoff marks (UR, OBC, SC, ST, EWS) and Tier 2 exam dates at ssc.gov.in.",
    },
    {
      title: "UPSC Civil Services IAS 2025 Final Result & Topper List Declared",
      slug: "upsc-ias-final-result-2025-2026",
      category: "results",
      subcategory: "UPSC",
      year: 2026,
      organization: "Union Public Service Commission",
      totalVacancies: "1,016 Posts",
      qualificationSummary: "IAS, IPS, IFS & Central Group A/B",
      shortDesc: "UPSC has published the Final Result and All India Rank (AIR) list of Civil Services Examination 2025. 1,016 candidates recommended for appointment.",
      status: "published",
      isPinned: true,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Prelims Exam Date", value: "28/05/2025" },
        { label: "Mains Exam Date", value: "15 to 24 September 2025" },
        { label: "Interview Date", value: "January - April 2026" },
        { label: "Final Result Date", value: "Released (Official)", isHighlight: true },
      ],
      applicationFee: [{ category: "Result Download", fee: "₹ 0/-" }],
      feePaymentMode: "Free to Download",
      ageLimit: { minAge: "21 Years", maxAge: "32 Years", asOnDate: "01/08/2025" },
      vacancyDetails: [
        { postName: "IAS Recommended", totalPosts: "180", eligibility: "Top Rankers based on Final Score", ageLimit: "21-32 Years" },
        { postName: "IFS Recommended", totalPosts: "37", eligibility: "Selected for Foreign Service", ageLimit: "21-32 Years" },
        { postName: "IPS Recommended", totalPosts: "200", eligibility: "Police Service Allocation", ageLimit: "21-32 Years" },
        { postName: "Central Group A & B", totalPosts: "599", eligibility: "Various Central Services", ageLimit: "21-32 Years" },
      ],
      importantLinks: [
        { label: "Download UPSC Final Result 2025 PDF (Name & Roll No. Wise)", url: "https://upsc.gov.in/examinations/final-results", linkType: "result", isHighlighted: true },
        { label: "Download IAS Toppers Marks List PDF", url: "https://upsc.gov.in", linkType: "result" },
        { label: "Official UPSC Portal", url: "https://upsc.gov.in", linkType: "official_website" },
      ],
      howToApply: ["Download the PDF", "Search your roll number", "Check allocated cadre and service"],
      selectionProcess: ["Final Rank list published based on Mains + Personality Test scores"],
      metaTitle: "UPSC Civil Services IAS Final Result 2025-2026 PDF Download Topper List",
      metaDescription: "UPSC CSE 2025 Final Result declared. Download merit list PDF with names, marks and ranks at upsc.gov.in.",
    },
    {
      title: "Railway RRB NTPC Graduate Level CBT 1 Result & Scorecard 2026",
      slug: "rrb-ntpc-cbt-1-result-2026",
      category: "results",
      subcategory: "Railway",
      year: 2026,
      organization: "Railway Recruitment Boards (RRB)",
      totalVacancies: "8,113 Posts",
      qualificationSummary: "Degree in Any Stream",
      shortDesc: "Railway Recruitment Boards have published Zone-wise RRB NTPC CBT-1 Exam Results, Cutoff Marks and CBT-2 Exam Schedules.",
      status: "published",
      isPinned: false,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "CBT 1 Exam Date", value: "November 2025" },
        { label: "Result Declaration", value: "Declared Today", isHighlight: true },
        { label: "CBT 2 Exam Date", value: "March 2026", isHighlight: true },
      ],
      applicationFee: [{ category: "Scorecard Login", fee: "₹ 0/-" }],
      feePaymentMode: "Free",
      ageLimit: { minAge: "18 Years", maxAge: "36 Years", asOnDate: "01/07/2026" },
      vacancyDetails: [
        { postName: "Station Master / Commercial Apprentice / Goods Train Manager", totalPosts: "8,113", eligibility: "Graduate Degree in Any Discipline", ageLimit: "18-36 Years" },
      ],
      importantLinks: [
        { label: "Check RRB NTPC CBT 1 Score Card (Login)", url: "https://rrbapply.gov.in", linkType: "result", isHighlighted: true },
        { label: "Download Zone-Wise Cut Off PDF (All RRBs)", url: "https://indianrailways.gov.in", linkType: "result" },
      ],
      howToApply: ["Enter Registration Number and Date of Birth on RRB login portal.", "Download the CBT 1 scorecard and check CBT 2 qualification status."],
      selectionProcess: ["CBT 1 (Cleared)", "CBT 2", "CBAT / Typing Skill Test", "Document Verification"],
      metaTitle: "Railway RRB NTPC Result 2026 CBT 1 Cutoff & Scorecard Download",
      metaDescription: "Download RRB NTPC CBT 1 result PDF and scorecard. Check zone-wise cutoff marks for Patna, Allahabad, Mumbai, Kolkata, Ranchi, Chennai.",
    },
    {
      title: "CTET January 2026 Result & Digilocker Marksheet Download",
      slug: "ctet-january-result-2026",
      category: "results",
      subcategory: "Teaching",
      year: 2026,
      organization: "Central Board of Secondary Education (CBSE)",
      totalVacancies: "National Eligibility Certificate",
      qualificationSummary: "D.El.Ed / B.Ed / Graduation",
      shortDesc: "CBSE has declared the Central Teacher Eligibility Test (CTET) January 2026 Result. Download marksheet and digital certificate via DigiLocker.",
      status: "published",
      isPinned: false,
      isNew: false,
      isUpdated: true,
      importantDates: [
        { label: "Exam Date", value: "21/01/2026" },
        { label: "Result Declared", value: "Available Now", isHighlight: true },
      ],
      applicationFee: [{ category: "Certificate Download", fee: "₹ 0/-" }],
      feePaymentMode: "Free via DigiLocker",
      ageLimit: { minAge: "18 Years", maxAge: "No Upper Age Limit", asOnDate: "2026" },
      vacancyDetails: [
        { postName: "CTET Paper 1 (Class I to V Primary)", totalPosts: "Certificate", eligibility: "12th with D.El.Ed OR B.El.Ed (60% qualifying score)", ageLimit: "18+ Years" },
        { postName: "CTET Paper 2 (Class VI to VIII Elementary)", totalPosts: "Certificate", eligibility: "Graduation with B.Ed / D.El.Ed (60% qualifying score)", ageLimit: "18+ Years" },
      ],
      importantLinks: [
        { label: "Check CTET January 2026 Result by Roll No.", url: "https://cbseresults.nic.in", linkType: "result", isHighlighted: true },
        { label: "Download DigiLocker Certificate", url: "https://digilocker.gov.in", linkType: "result" },
      ],
      howToApply: ["Enter Roll Number on cbseresults.nic.in", "View Paper 1 & 2 marks statement", "Log in to DigiLocker to save digitally signed certificate"],
      selectionProcess: ["Qualifying Exam (60% for General, 55% for Reserved Categories)"],
      metaTitle: "CTET Result January 2026 Out - Check Score at ctet.nic.in & DigiLocker",
      metaDescription: "CBSE CTET 2026 Result download link, passing marks and DigiLocker certificate release date.",
    },

    // --- ADMIT CARD ---
    {
      title: "Railway RRB ALP Admit Card 2026 & Exam City Intimation Slip",
      slug: "rrb-alp-admit-card-2026",
      category: "admit-card",
      subcategory: "Railway",
      year: 2026,
      organization: "Railway Recruitment Boards",
      totalVacancies: "18,799 Posts",
      qualificationSummary: "10th + ITI / Diploma / Degree",
      shortDesc: "RRB Assistant Loco Pilot CEN 01/2026 CBT 1 E-Call Letter and Exam City Slip available for download 4 days prior to exam date.",
      status: "published",
      isPinned: true,
      isNew: true,
      isUpdated: true,
      importantDates: [
        { label: "City Slip Live Date", value: "10 Days before Exam", isHighlight: true },
        { label: "Admit Card Download", value: "4 Days before Exam", isHighlight: true },
        { label: "Exam Dates", value: "25 November to 29 November 2026" },
      ],
      applicationFee: [{ category: "Hall Ticket Download", fee: "₹ 0/-" }],
      feePaymentMode: "Free",
      ageLimit: { minAge: "18 Years", maxAge: "33 Years", asOnDate: "01/07/2026" },
      vacancyDetails: [
        { postName: "Assistant Loco Pilot (ALP)", totalPosts: "18,799", eligibility: "Eligible candidates who submitted valid applications", ageLimit: "18-33 Years" },
      ],
      importantLinks: [
        { label: "Download RRB ALP Admit Card (Login)", url: "https://www.rrbapply.gov.in", linkType: "admit_card", isHighlighted: true },
        { label: "Check Exam City & Date Slip", url: "https://www.rrbapply.gov.in", linkType: "admit_card", isHighlighted: true },
        { label: "Download Free Travel Pass (SC/ST Candidates)", url: "https://www.rrbapply.gov.in", linkType: "admit_card" },
        { label: "Official Railway Portal", url: "https://indianrailways.gov.in", linkType: "official_website" },
      ],
      howToApply: [
        "Visit the official RRB website rrbapply.gov.in.",
        "Enter your Registration Number and Password / Date of Birth.",
        "Click on the 'City Intimation / E-Call Letter' tab.",
        "Verify your exam date, shift timing, reporting time and exam center address.",
        "Download and print colored copy of the Admit Card. Note: Carry Aadhaar Card for Biometric Verification.",
      ],
      selectionProcess: ["CBT 1 Exam", "CBT 2 Exam", "CBAT (Aptitude Test)", "Document Verification"],
      metaTitle: "RRB ALP Admit Card 2026 Download - Railway ALP CBT 1 Hall Ticket & City Slip",
      metaDescription: "Download RRB Assistant Loco Pilot Admit Card 2026 and check exam city intimation slip at rrbapply.gov.in.",
    },
    {
      title: "UPSC NDA & NA (I) 2026 Admit Card / Hall Ticket Released",
      slug: "upsc-nda-1-admit-card-2026",
      category: "admit-card",
      subcategory: "Defense",
      year: 2026,
      organization: "Union Public Service Commission",
      totalVacancies: "400 Posts",
      qualificationSummary: "10+2 Passed / Appearing",
      shortDesc: "UPSC has issued e-Admit Cards for National Defence Academy & Naval Academy Examination (I) 2026.",
      status: "published",
      isPinned: false,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Admit Card Released", value: "Available Now", isHighlight: true },
        { label: "Exam Date", value: "19/04/2026", isHighlight: true },
      ],
      applicationFee: [{ category: "Hall Ticket Download", fee: "₹ 0/-" }],
      feePaymentMode: "Free",
      ageLimit: { minAge: "Born between 02/07/2007 and 01/07/2010", maxAge: "19.5 Years", asOnDate: "2026" },
      vacancyDetails: [
        { postName: "National Defence Academy (Army, Navy, Air Force)", totalPosts: "400", eligibility: "12th Class Pass of 10+2 pattern (Physics & Maths for Navy/Air Force)", ageLimit: "16.5-19.5 Years" },
      ],
      importantLinks: [
        { label: "Download UPSC NDA 1 Admit Card (By Roll No / Reg ID)", url: "https://upsconline.nic.in/eadmitcard", linkType: "admit_card", isHighlighted: true },
        { label: "Official UPSC Website", url: "https://upsc.gov.in", linkType: "official_website" },
      ],
      howToApply: ["Enter Registration ID or Roll Number with Date of Birth on upsconline.nic.in.", "Print the e-admit card on A4 paper along with instructions sheet."],
      selectionProcess: ["Written Examination (Mathematics 300 Marks + GAT 600 Marks)", "SSB Interview (5 Days - 900 Marks)", "Medical Examination"],
      metaTitle: "UPSC NDA 1 Admit Card 2026 Download Hall Ticket at upsc.gov.in",
      metaDescription: "Download UPSC National Defence Academy NDA (I) 2026 admit card, check exam center and shift instructions.",
    },
    {
      title: "NTA JEE Main Session 2 Admit Card 2026 Download",
      slug: "nta-jee-main-session-2-admit-card-2026",
      category: "admit-card",
      subcategory: "NTA",
      year: 2026,
      organization: "National Testing Agency (NTA)",
      totalVacancies: "Engineering Entrance Exam",
      qualificationSummary: "10+2 with PCM",
      shortDesc: "National Testing Agency has released the Session 2 Admit Card for Joint Entrance Examination (Main) 2026.",
      status: "published",
      isPinned: false,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Session 2 Exam Dates", value: "04 to 15 April 2026", isHighlight: true },
        { label: "Admit Card Available", value: "Live Now", isHighlight: true },
      ],
      applicationFee: [{ category: "Hall Ticket", fee: "₹ 0/-" }],
      feePaymentMode: "Free",
      ageLimit: { minAge: "No Age Limit", maxAge: "12th Pass 2024, 2025, or Appearing 2026", asOnDate: "2026" },
      vacancyDetails: [
        { postName: "JEE Main 2026 Paper 1 (B.E. / B.Tech)", totalPosts: "Entrance Exam", eligibility: "10+2 with Physics, Mathematics, Chemistry", ageLimit: "N/A" },
      ],
      importantLinks: [
        { label: "Download JEE Main Session 2 Admit Card", url: "https://jeemain.nta.ac.in", linkType: "admit_card", isHighlighted: true },
        { label: "Official NTA JEE Portal", url: "https://jeemain.nta.ac.in", linkType: "official_website" },
      ],
      howToApply: ["Login with Application Number and Date of Birth.", "Download admit card with undertaking and affix passport size photo."],
      selectionProcess: ["Computer Based Test (CBT) across India and International test cities"],
      metaTitle: "JEE Main Session 2 Admit Card 2026 Download at jeemain.nta.ac.in",
      metaDescription: "Direct link to download NTA JEE Main 2026 Session 2 Hall Ticket, check exam day guidelines and shift timings.",
    },

    // --- ANSWER KEY ---
    {
      title: "SSC GD Constable 2026 Official Answer Key & Response Sheet",
      slug: "ssc-gd-constable-answer-key-2026",
      category: "answer-key",
      subcategory: "SSC",
      year: 2026,
      organization: "Staff Selection Commission (SSC)",
      totalVacancies: "39,481 Posts",
      qualificationSummary: "10th High School Exam Passed",
      shortDesc: "SSC has released tentative answer keys along with candidate response sheets for Constable (GD) in Central Armed Police Forces (CAPFs), SSF, and Rifleman in Assam Rifles.",
      status: "published",
      isPinned: true,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Computer Exam Date", value: "February - March 2026" },
        { label: "Answer Key Released", value: "Released (Official)", isHighlight: true },
        { label: "Objection Last Date", value: "10 April 2026 upto 05:00 PM", isHighlight: true },
      ],
      applicationFee: [
        { category: "Answer Key Check", fee: "₹ 0/- (Free)" },
        { category: "Per Question Challenge Fee", fee: "₹ 100/- per question challenged" },
      ],
      feePaymentMode: "Online Payment for Objections",
      ageLimit: { minAge: "18 Years", maxAge: "23 Years", asOnDate: "01/01/2026" },
      vacancyDetails: [
        { postName: "Constable GD (BSF, CISF, CRPF, SSB, ITBP, AR, SSF)", totalPosts: "39,481", eligibility: "10th Class Exam Passed from recognized Board", ageLimit: "18-23 Years" },
      ],
      importantLinks: [
        { label: "Download SSC GD Answer Key & Response Sheet (Login)", url: "https://ssc.gov.in/answerkey", linkType: "answer_key", isHighlighted: true },
        { label: "Submit Online Objections / Challenges", url: "https://ssc.gov.in", linkType: "answer_key" },
        { label: "Official SSC Website", url: "https://ssc.gov.in", linkType: "official_website" },
      ],
      howToApply: [
        "Click on the official answer key link above.",
        "Enter your Roll Number / User ID and Password as mentioned on the SSC GD Admit Card.",
        "Your question paper along with marked responses and correct answers will appear.",
        "Calculate your estimated raw score (Each correct answer +2 marks, negative marking 0.25 marks).",
        "If any answer is incorrect, click on 'Raise Objection' and pay ₹100 per question.",
      ],
      selectionProcess: ["Computer Based Examination (CBE)", "Physical Standard Test (PST)", "Physical Efficiency Test (PET)", "Detailed Medical Examination (DME)"],
      metaTitle: "SSC GD Constable Answer Key 2026 Out - Response Sheet & Score Calculator",
      metaDescription: "Download SSC GD 2026 Answer Key PDF, response sheet and check raw score calculation method at ssc.gov.in.",
    },
    {
      title: "UGC NET December 2025 Provisional Answer Key & Question Paper",
      slug: "ugc-net-december-answer-key-2025-2026",
      category: "answer-key",
      subcategory: "NTA",
      year: 2026,
      organization: "National Testing Agency (NTA)",
      totalVacancies: "Assistant Professor & JRF",
      qualificationSummary: "Master Degree with 55% Marks",
      shortDesc: "NTA has uploaded the provisional answer keys and recorded responses for UGC NET December cycle across 83 subjects.",
      status: "published",
      isPinned: false,
      isNew: false,
      isUpdated: true,
      importantDates: [
        { label: "Answer Key Live", value: "Available Now", isHighlight: true },
        { label: "Challenge Window", value: "Open till 3 Days" },
      ],
      applicationFee: [{ category: "Challenge Fee", fee: "₹ 200/- per question (Non-refundable)" }],
      feePaymentMode: "Online via UPI/Netbanking",
      ageLimit: { minAge: "No limit for Asst. Prof", maxAge: "30 Years for JRF", asOnDate: "2026" },
      vacancyDetails: [
        { postName: "Junior Research Fellowship (JRF) & Assistant Professor", totalPosts: "National Eligibility", eligibility: "Master Degree or equivalent with 55% marks (50% for SC/ST/OBC)", ageLimit: "Up to 30 Yrs (JRF)" },
      ],
      importantLinks: [
        { label: "Download UGC NET Answer Key & Response Sheet", url: "https://ugcnet.nta.ac.in", linkType: "answer_key", isHighlighted: true },
        { label: "Official UGC NET Portal", url: "https://ugcnet.nta.ac.in", linkType: "official_website" },
      ],
      howToApply: ["Login with Application Number and Password on ugcnet.nta.ac.in", "View question paper and key", "Submit challenges if any"],
      selectionProcess: ["CBT Exam across 83 subjects"],
      metaTitle: "UGC NET Answer Key 2026 Download Response Sheet at ugcnet.nta.ac.in",
      metaDescription: "NTA UGC NET provisional answer key, question paper PDF download and challenge link.",
    },

    // --- SYLLABUS ---
    {
      title: "UPSC IAS Preliminary & Main Exam Complete Syllabus & Pattern 2026",
      slug: "upsc-ias-exam-syllabus-2026",
      category: "syllabus",
      subcategory: "UPSC",
      year: 2026,
      organization: "Union Public Service Commission",
      totalVacancies: "Civil Services Exam",
      qualificationSummary: "Degree in Any Stream",
      shortDesc: "Complete topic-wise syllabus and exam pattern for UPSC Civil Services Prelims (GS Paper I & CSAT), Mains (9 Papers) and Optional subjects in English and Hindi.",
      status: "published",
      isPinned: true,
      isNew: false,
      isUpdated: true,
      importantDates: [
        { label: "Prelims Exam Date", value: "24/05/2026", isHighlight: true },
        { label: "Mains Exam Date", value: "September 2026" },
      ],
      applicationFee: [{ category: "Syllabus Download", fee: "₹ 0/- (Free PDF)" }],
      feePaymentMode: "Free to Download",
      ageLimit: { minAge: "21 Years", maxAge: "32 Years", asOnDate: "01/08/2026" },
      vacancyDetails: [
        { postName: "Civil Services Examination 2026", totalPosts: "1,105", eligibility: "Graduation in Any Discipline", ageLimit: "21-32 Years" },
      ],
      importantLinks: [
        { label: "Download Complete UPSC CSE Syllabus PDF (English)", url: "https://upsc.gov.in/sites/default/files/Syllabus-CSE.pdf", linkType: "syllabus", isHighlighted: true },
        { label: "Download UPSC Previous 10 Years Question Papers", url: "https://upsc.gov.in/examinations/previous-question-papers", linkType: "syllabus" },
        { label: "Official UPSC Website", url: "https://upsc.gov.in", linkType: "official_website" },
      ],
      howToApply: [
        "Download the official PDF syllabus using the link above.",
        "Analyze Prelims weightage: History, Geography, Polity, Economy, Environment, Science & Tech, Current Affairs.",
        "Prepare GS Papers 1 to 4 and choose Optional subject carefully.",
      ],
      selectionProcess: ["Prelims (400 Marks)", "Mains (1750 Marks)", "Interview (275 Marks) = Total 2025 Marks"],
      metaTitle: "UPSC IAS Syllabus 2026 PDF Download - Prelims & Mains Exam Pattern",
      metaDescription: "Download latest UPSC Civil Services IAS exam syllabus 2026, marking scheme, topic-wise breakdown and previous question papers.",
    },
    {
      title: "SSC CGL 2026 Tier 1 & Tier 2 Detailed Syllabus & Exam Pattern",
      slug: "ssc-cgl-syllabus-exam-pattern-2026",
      category: "syllabus",
      subcategory: "SSC",
      year: 2026,
      organization: "Staff Selection Commission",
      totalVacancies: "17,727 Vacancies",
      qualificationSummary: "Graduation in Any Subject",
      shortDesc: "Check latest revised exam pattern for SSC CGL Tier 1 & Tier 2: Reasoning, General Awareness, Quantitative Aptitude, English Comprehension, Computer Knowledge & Typing module.",
      status: "published",
      isPinned: false,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Exam Mode", value: "Computer Based (CBT)" },
        { label: "Negative Marking", value: "0.50 marks (Tier 1) / 1 mark (Tier 2)" },
      ],
      applicationFee: [{ category: "Syllabus Download", fee: "₹ 0/-" }],
      feePaymentMode: "Free",
      ageLimit: { minAge: "18 Years", maxAge: "32 Years", asOnDate: "2026" },
      vacancyDetails: [
        { postName: "Group B & C Posts", totalPosts: "17,727", eligibility: "Graduation", ageLimit: "18-32 Years" },
      ],
      importantLinks: [
        { label: "Download SSC CGL Detailed Syllabus PDF", url: "https://ssc.gov.in", linkType: "syllabus", isHighlighted: true },
      ],
      howToApply: ["Download syllabus PDF and create daily subject schedule."],
      selectionProcess: ["Tier 1: 100 Questions (200 Marks) in 60 mins", "Tier 2: Mathematical Abilities, Reasoning, English, General Awareness, Computer & Typing"],
      metaTitle: "SSC CGL Syllabus 2026 PDF Download - Tier 1 & 2 Subject-wise Pattern",
      metaDescription: "Check SSC CGL 2026 detailed syllabus for Quant, Reasoning, English, GS & Computer with PDF download.",
    },

    // --- ADMISSION ---
    {
      title: "NTA NEET UG 2026 Medical Entrance Exam Online Application Form",
      slug: "nta-neet-ug-admission-2026",
      category: "admission",
      subcategory: "NTA",
      year: 2026,
      organization: "National Testing Agency (NTA)",
      totalVacancies: "MBBS / BDS / AYUSH Admissions",
      qualificationSummary: "10+2 with Physics, Chemistry & Biology (PCB)",
      shortDesc: "National Eligibility cum Entrance Test (UG) 2026 for admission to undergraduate medical courses (MBBS / BDS / BAMS / BHMS / BUMS / BSMS) in all approved medical colleges across India.",
      status: "published",
      isPinned: true,
      isNew: true,
      isUpdated: true,
      importantDates: [
        { label: "Application Start", value: "09/02/2026" },
        { label: "Last Date to Apply", value: "15/04/2026 upto 09:00 PM", isHighlight: true },
        { label: "Fee Payment Last Date", value: "15/04/2026 upto 11:50 PM" },
        { label: "Correction Window", value: "18 to 22 April 2026" },
        { label: "Exam Date", value: "03/05/2026 (Sunday)", isHighlight: true },
        { label: "Result Declaration", value: "June 2026" },
      ],
      applicationFee: [
        { category: "General Candidates", fee: "₹ 1,700/-" },
        { category: "General-EWS / OBC-NCL", fee: "₹ 1,600/-" },
        { category: "SC / ST / PwBD / Third Gender", fee: "₹ 1,000/-" },
        { category: "Centres Outside India", fee: "₹ 9,500/-" },
      ],
      feePaymentMode: "Online Payment through Credit Card / Debit Card / Net Banking / UPI.",
      ageLimit: {
        minAge: "Minimum 17 Years completed on or before 31st December 2026 (Born on or before 31/12/2009)",
        maxAge: "No Upper Age Limit as per NMC guidelines",
        asOnDate: "31/12/2026",
      },
      vacancyDetails: [
        { postName: "MBBS / BDS / BAMS / BHMS Admission 2026-27", totalPosts: "1,08,000+ Medical Seats", eligibility: "Passed 10+2 Intermediate with Physics, Chemistry, Biology / Biotechnology and English as core subjects with minimum 50% marks (40% for SC/ST/OBC).", ageLimit: "Min 17 Years" },
      ],
      importantLinks: [
        { label: "Apply Online for NEET UG 2026 (Registration / Login)", url: "https://neet.ntaonline.in", linkType: "apply", isHighlighted: true },
        { label: "Download NEET UG 2026 Information Bulletin (PDF)", url: "https://exams.nta.ac.in/NEET", linkType: "notification" },
        { label: "Official NTA NEET Website", url: "https://exams.nta.ac.in/NEET", linkType: "official_website" },
      ],
      howToApply: [
        "Step 1: Apply for Online Registration using unique Email Id and Mobile No on neet.ntaonline.in.",
        "Step 2: Fill in the Online Application Form and note down the system-generated Application Number.",
        "Step 3: Upload scanned images: Candidate Photograph (passport & postcard), Signature, Left and Right-hand Fingers and Thumb impressions.",
        "Step 4: Pay the fee using Payment Gateway through Net Banking / Debit Card / Credit Card / UPI.",
        "Step 5: Download and save the Confirmation Page of the Application Form for future reference.",
      ],
      selectionProcess: ["Pen and Paper (OMR) Based Test comprising 200 multiple choice questions (Physics, Chemistry, Botany, Zoology)"],
      metaTitle: "NEET UG 2026 Online Form - Eligibility, Exam Date, Syllabus & Apply Online",
      metaDescription: "NTA NEET UG 2026 registration link, eligibility criteria, application fee, exam pattern and information bulletin PDF download.",
    },
    {
      title: "CUET UG 2026 Common University Entrance Test Registration",
      slug: "cuet-ug-admission-form-2026",
      category: "admission",
      subcategory: "NTA",
      year: 2026,
      organization: "National Testing Agency (NTA)",
      totalVacancies: "Central & State University Admissions",
      qualificationSummary: "10+2 Appearing / Passed",
      shortDesc: "Common University Entrance Test (CUET-UG 2026) for admission into all Central Universities (DU, BHU, JNU, JMI, AU) and participating institutions.",
      status: "published",
      isPinned: false,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Application Start", value: "28/02/2026" },
        { label: "Last Date to Apply", value: "05/04/2026", isHighlight: true },
        { label: "Exam Date", value: "15 to 31 May 2026", isHighlight: true },
      ],
      applicationFee: [
        { category: "General (up to 3 subjects)", fee: "₹ 1,000/-" },
        { category: "OBC-NCL / EWS (up to 3 subjects)", fee: "₹ 900/-" },
        { category: "SC / ST / PwBD (up to 3 subjects)", fee: "₹ 800/-" },
      ],
      feePaymentMode: "Online Payment Gateway",
      ageLimit: { minAge: "No Age Limit", maxAge: "10+2 Passed or Appearing", asOnDate: "2026" },
      vacancyDetails: [
        { postName: "Undergraduate Degree Courses (BA, B.Sc, B.Com, BBA, BCA, B.Tech)", totalPosts: "All Central Universities", eligibility: "10+2 passed or appearing in 2026.", ageLimit: "No Limit" },
      ],
      importantLinks: [
        { label: "Apply Online for CUET UG 2026", url: "https://cuetug.ntaonline.in", linkType: "apply", isHighlighted: true },
        { label: "Download CUET UG 2026 Information Brochure", url: "https://exams.nta.ac.in/CUET-UG", linkType: "notification" },
      ],
      howToApply: ["Register on cuetug.ntaonline.in", "Select university and course preferences", "Choose domain test subjects", "Pay application fee"],
      selectionProcess: ["Hybrid (CBT & OMR) Examination based on Class 12 syllabus"],
      metaTitle: "CUET UG 2026 Registration Open - DU, BHU, JNU Admissions Apply Online",
      metaDescription: "Apply online for CUET UG 2026 entrance exam for Central Universities admission, exam pattern and test schedule.",
    },

    // --- ENGINEERING JOBS ---
    {
      title: "SSC JE (Junior Engineer) Recruitment 2026 (Civil, Mech, Elec - 968 Posts)",
      slug: "ssc-je-junior-engineer-recruitment-2026",
      category: "engineering",
      subcategory: "SSC",
      year: 2026,
      organization: "Staff Selection Commission (SSC)",
      totalVacancies: "968 Posts",
      qualificationSummary: "Diploma / Degree in Civil, Electrical, Mechanical Engineering",
      shortDesc: "SSC Junior Engineer (Civil, Mechanical & Electrical) Examination 2026 for CPWD, CWC, MES, Border Roads Organization (BRO), and NTRO.",
      status: "published",
      isPinned: true,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Application Start", value: "28/03/2026" },
        { label: "Last Date to Apply", value: "25/04/2026", isHighlight: true },
        { label: "Paper 1 Exam Date", value: "June / July 2026", isHighlight: true },
      ],
      applicationFee: [
        { category: "General / OBC / EWS", fee: "₹ 100/-" },
        { category: "SC / ST / PH / Female", fee: "₹ 0/- (Nil)" },
      ],
      feePaymentMode: "Online via BHIM UPI, Net Banking, Cards",
      ageLimit: { minAge: "18 Years", maxAge: "30-32 Years (Dept. Wise)", asOnDate: "01/08/2026" },
      vacancyDetails: [
        { postName: "Junior Engineer (Civil) - CPWD, MES, BRO", totalPosts: "620", eligibility: "Diploma or B.Tech / B.E. in Civil Engineering with relevant experience for BRO/MES.", ageLimit: "Up to 30-32 Years" },
        { postName: "Junior Engineer (Electrical & Mechanical)", totalPosts: "348", eligibility: "Diploma or B.Tech / B.E. in Electrical or Mechanical Engineering.", ageLimit: "Up to 30 Years" },
      ],
      importantLinks: [
        { label: "Apply Online (SSC Portal)", url: "https://ssc.gov.in", linkType: "apply", isHighlighted: true },
        { label: "Download Official SSC JE Notification PDF", url: "https://ssc.gov.in", linkType: "notification" },
        { label: "Official Website", url: "https://ssc.gov.in", linkType: "official_website" },
      ],
      howToApply: ["Register on ssc.gov.in", "Select engineering branch and post preferences", "Pay ₹100 fee and download confirmation"],
      selectionProcess: ["Paper 1 CBT (Objective)", "Paper 2 CBT (Subject Specific 300 Marks)", "Document Verification"],
      metaTitle: "SSC JE Recruitment 2026 - 968 Junior Engineer Posts Apply Online",
      metaDescription: "SSC JE 2026 notification for Civil, Mechanical, Electrical branches. Eligibility, vacancy details, syllabus and online application link.",
    },
    {
      title: "ISRO Scientist / Engineer 'SC' Direct Recruitment 2026",
      slug: "isro-scientist-engineer-sc-recruitment-2026",
      category: "engineering",
      subcategory: "Engineering",
      year: 2026,
      organization: "Indian Space Research Organisation (ISRO ICRB)",
      totalVacancies: "303 Posts",
      qualificationSummary: "BE / B.Tech in Electronics, Mechanical, Computer Science (65% or 6.84 CGPA)",
      shortDesc: "ISRO Centralised Recruitment Board invites applications for the post of Scientist/Engineer 'SC' in Level 10 of Pay Matrix (₹ 56,100 - ₹ 1,77,500).",
      status: "published",
      isPinned: false,
      isNew: true,
      isUpdated: false,
      importantDates: [
        { label: "Application Start", value: "15/03/2026" },
        { label: "Last Date to Apply", value: "05/04/2026", isHighlight: true },
        { label: "Written Exam Date", value: "June 2026" },
      ],
      applicationFee: [
        { category: "All Candidates Application Fee", fee: "₹ 250/- (Refundable ₹150 for non-exempted upon appearing in test)" },
        { category: "Women / SC / ST / PwD / Ex-SM", fee: "₹ 250/- (100% Refundable upon appearing)" },
      ],
      feePaymentMode: "Online Payment via SBI e-Pay",
      ageLimit: { minAge: "18 Years", maxAge: "28 Years", asOnDate: "05/04/2026" },
      vacancyDetails: [
        { postName: "Scientist/Engineer 'SC' (Electronics)", totalPosts: "90", eligibility: "BE/B.Tech in Electronics & Communication with First Class (min 65% or 6.84 CGPA).", ageLimit: "18-28 Years" },
        { postName: "Scientist/Engineer 'SC' (Mechanical)", totalPosts: "163", eligibility: "BE/B.Tech in Mechanical Engineering with First Class.", ageLimit: "18-28 Years" },
        { postName: "Scientist/Engineer 'SC' (Computer Science)", totalPosts: "50", eligibility: "BE/B.Tech in Computer Science / IT with First Class.", ageLimit: "18-28 Years" },
      ],
      importantLinks: [
        { label: "Apply Online (ISRO ICRB Portal)", url: "https://www.isro.gov.in/careers", linkType: "apply", isHighlighted: true },
        { label: "Download ISRO Advt Notification PDF", url: "https://www.isro.gov.in", linkType: "notification" },
      ],
      howToApply: ["Register on ISRO careers portal", "Enter academic CGPA details accurately", "Pay application processing fee"],
      selectionProcess: ["Written Test (Part A Area Discipline + Part B Aptitude)", "Personal Interview (Minimum 50% qualifying score)"],
      metaTitle: "ISRO Scientist Engineer SC Recruitment 2026 Apply Online 303 Posts",
      metaDescription: "Indian Space Research Organisation Scientist Engineer 2026 recruitment notification, salary, qualification and apply link.",
    },
    {
      title: "GATE 2026 PSU Recruitment: IOCL, ONGC, NTPC, BHEL Executive Trainee",
      slug: "gate-2026-psu-recruitment-notification",
      category: "engineering",
      subcategory: "Engineering",
      year: 2026,
      organization: "Public Sector Undertakings (PSUs)",
      totalVacancies: "2,500+ PSU Trainee Posts",
      qualificationSummary: "B.Tech / B.E. + Valid GATE 2026 Score",
      shortDesc: "Top Maharatna & Navratna PSUs announce Executive Trainee, Management Trainee & Graduate Apprentice positions through GATE 2026 Score.",
      status: "published",
      isPinned: false,
      isNew: false,
      isUpdated: true,
      importantDates: [
        { label: "GATE Exam Completed", value: "February 2026" },
        { label: "PSU Applications Begin", value: "March - April 2026", isHighlight: true },
      ],
      applicationFee: [{ category: "Varies by PSU (IOCL/ONGC: ₹300, NTPC: ₹300, SC/ST: Nil)", fee: "₹ 0 - ₹ 300" }],
      feePaymentMode: "Respective PSU Online Portals",
      ageLimit: { minAge: "21 Years", maxAge: "26-28 Years", asOnDate: "2026" },
      vacancyDetails: [
        { postName: "IOCL Officers / Engineers", totalPosts: "550", eligibility: "B.Tech in Chemical, Civil, Electrical, Mech + GATE 2026", ageLimit: "Max 26 Years" },
        { postName: "ONGC Graduate Trainee (Class I Executive)", totalPosts: "620", eligibility: "B.Tech in Petroleum, Mech, Elec, Geo + GATE 2026", ageLimit: "Max 28 Years" },
        { postName: "NTPC Engineering Executive Trainee (EET)", totalPosts: "480", eligibility: "B.Tech with 65% Marks + GATE 2026", ageLimit: "Max 27 Years" },
      ],
      importantLinks: [
        { label: "Check IOCL Recruitment Portal", url: "https://iocl.com/careers", linkType: "apply", isHighlighted: true },
        { label: "Check ONGC GATE Careers", url: "https://ongcindia.com/careers", linkType: "apply" },
        { label: "Check NTPC Careers Portal", url: "https://careers.ntpc.co.in", linkType: "apply" },
      ],
      howToApply: ["Register on respective PSU career portal with GATE 2026 Registration Number and Scorecard."],
      selectionProcess: ["Shortlisting based on GATE 2026 Normalized Marks followed by GD & Personal Interview"],
      metaTitle: "GATE 2026 PSU Recruitment List - IOCL, ONGC, NTPC, BHEL 2500+ Posts",
      metaDescription: "List of PSUs recruiting through GATE 2026 score, application dates, vacancies and eligibility requirements.",
    },
  ];

  for (const post of samplePosts) {
    const existing = await db.select().from(posts).where(eq(posts.slug, post.slug));
    if (existing.length === 0) {
      await db.insert(posts).values({
        ...post,
        viewsCount: Math.floor(Math.random() * 5000) + 1200,
      });
    }
  }
  console.log(`✅ Seeded ${samplePosts.length} posts across all categories`);
  console.log("🎉 Seeding completed successfully!");
}

export default runSeed;
